import React from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';

export default function DisclaimerPage() {
  return (
    <div className="container max-w-4xl mx-auto py-8 px-4">
      <h1 className="text-3xl font-bold mb-8 text-center">Legal Disclaimer</h1>
      
      <Card className="mb-6">
        <CardHeader>
          <CardTitle>IMPORTANT DISCLAIMER</CardTitle>
        </CardHeader>
        <CardContent className="prose">
          <p className="mb-4">
            Last updated: April 17, 2025
          </p>
          
          <h2 className="text-xl font-semibold mt-4 mb-2">NOT LEGAL ADVICE</h2>
          <p>
            The information provided on Pocket Lawyer is for general informational and educational purposes only. 
            It is not intended to be and should not be construed as legal advice. Pocket Lawyer is not a law firm 
            and is not a substitute for an attorney or law firm. Use of the platform does not create an attorney-client 
            relationship.
          </p>
          
          <h2 className="text-xl font-semibold mt-4 mb-2">AI-GENERATED CONTENT LIMITATIONS</h2>
          <p>
            The automated responses generated by our AI technology are based on pattern recognition and general 
            legal information. The AI does not possess legal expertise, cannot provide personalized legal advice, 
            and may not account for all relevant facts, changes in the law, jurisdictional differences, or your 
            specific circumstances.
          </p>
          
          <h2 className="text-xl font-semibold mt-4 mb-2">LAWYER DIRECTORY AND CONSULTATION</h2>
          <p>
            While Pocket Lawyer may provide a platform for connecting users with licensed attorneys, we do not:
          </p>
          <ul className="list-disc pl-6">
            <li>Guarantee the quality, accuracy, or appropriateness of any legal advice provided by these attorneys</li>
            <li>Make representations regarding their expertise, experience, or qualifications</li>
            <li>Take responsibility for the outcome of any legal consultation</li>
            <li>Guarantee availability of legal professionals in your jurisdiction</li>
          </ul>
          <p>
            Any communication with attorneys found through our platform establishes an attorney-client relationship 
            directly between you and that attorney, not with Pocket Lawyer.
          </p>
          
          <h2 className="text-xl font-semibold mt-4 mb-2">CONSULT A QUALIFIED ATTORNEY</h2>
          <p>
            For legal advice specific to your situation, we strongly recommend consulting with a qualified attorney 
            licensed to practice in your jurisdiction. Legal matters are often complex and fact-specific, and 
            relying solely on general information or AI-generated content may not adequately protect your rights 
            or interests.
          </p>
          
          <h2 className="text-xl font-semibold mt-4 mb-2">JURISDICTIONAL LIMITATIONS</h2>
          <p>
            Laws vary significantly by jurisdiction (country, state, locality). The information provided may not 
            be applicable to your specific jurisdiction or circumstances, and you should verify any information 
            with respect to your local laws.
          </p>
        </CardContent>
      </Card>
    </div>
  );
}